/*
 * lib_gpio.h
 *
 *  Created on: 26/10/2017
 *      Author: carlo
 */

#ifndef MAL_LIB_GPIO_H_
#define MAL_LIB_GPIO_H_

#include "S32K144.h"
#include "MAL/def_lib.h"

//void PORTA_SET_INPUT(T_ULONG PIN);
void PORTB_SET_INPUT(T_ULONG PIN);
void PORTC_SET_INPUT(T_ULONG PIN);
void PORTD_SET_INPUT(T_ULONG PIN);
void PORTE_SET_INPUT(T_ULONG PIN);

//void PORTA_SET_OUTPUT(T_ULONG PIN);
void PORTB_SET_OUTPUT(T_ULONG PIN);
void PORTC_SET_OUTPUT(T_ULONG PIN);
void PORTD_SET_OUTPUT(T_ULONG PIN);
void PORTE_SET_OUTPUT(T_ULONG PIN);

//void PORTA_OUTPUT_HIGH(T_ULONG PIN);
void PORTB_OUTPUT_HIGH(T_ULONG PIN);
void PORTC_OUTPUT_HIGH(T_ULONG PIN);
void PORTD_OUTPUT_HIGH(T_ULONG PIN);
void PORTE_OUTPUT_HIGH(T_ULONG PIN);

//void PORTA_OUTPUT_LOW(T_ULONG PIN);
void PORTB_OUTPUT_LOW(T_ULONG PIN);
void PORTC_OUTPUT_LOW(T_ULONG PIN);
void PORTD_OUTPUT_LOW(T_ULONG PIN);
void PORTE_OUTPUT_LOW(T_ULONG PIN);

//void PORTA_OUTPUT_TOGGLE(T_ULONG PIN);
void PORTB_OUTPUT_TOGGLE(T_ULONG PIN);
void PORTC_OUTPUT_TOGGLE(T_ULONG PIN);
void PORTD_OUTPUT_TOGGLE(T_ULONG PIN);
void PORTE_OUTPUT_TOGGLE(T_ULONG PIN);

//T_UBYTE PORTA_INPUT(T_ULONG PIN);
T_ULONG PORTB_INPUT(T_ULONG PIN);
T_ULONG PORTC_INPUT(T_ULONG PIN);
T_ULONG PORTD_INPUT(T_ULONG PIN);
T_ULONG PORTE_INPUT(T_ULONG PIN);
#endif /* MAL_LIB_GPIO_H_ */
